"""empty message

Revision ID: 6ec7f5becbf5
Revises: d8b755bd4ba7
Create Date: 2026-03-17 22:41:48.956160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec7f5becbf5'
down_revision = 'd8b755bd4ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_email_code_email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_email_code_email'), ['email'], unique=True)

    # ### end Alembic commands ###
